/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/flower.glb 
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

function Model(props: any) {
  const flowerRef = useRef<any>();
  const { nodes, materials } = useGLTF('/flower.glb')

  useFrame(() => {
    if(flowerRef.current) flowerRef.current.rotation.y += 0.01;
  });

  console.log("🚀 ~ Model ~ nodes:", nodes)
  return (
    <group {...props} dispose={null}>
      <mesh ref={flowerRef} geometry={nodes.Flower_Sunflower_Medium.geometry} material={materials.M_Flower_Sunflower} position={[0,-2.5,0]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/flower.glb')
export { Model }